name: bloctutorial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  http: ^1.3.0
  internet_connection_checker_plus: ^2.7.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
